// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJr-kvH2QasUzS4TcY9Vra5VJDpzTdSj8',
    appId: '1:878715841820:web:1e479824616bf1c5dbded9',
    messagingSenderId: '878715841820',
    projectId: 'skillboxfirebase-cee89',
    authDomain: 'skillboxfirebase-cee89.firebaseapp.com',
    storageBucket: 'skillboxfirebase-cee89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZhx6jBsQzVaP9eEBCWUErVa7QO1yIXE',
    appId: '1:878715841820:android:cea274bd33b70871dbded9',
    messagingSenderId: '878715841820',
    projectId: 'skillboxfirebase-cee89',
    storageBucket: 'skillboxfirebase-cee89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAczZs5PU0mxcSky5qH4bX56Jw5ZNZSZdg',
    appId: '1:878715841820:ios:45c222eccc2a1eefdbded9',
    messagingSenderId: '878715841820',
    projectId: 'skillboxfirebase-cee89',
    storageBucket: 'skillboxfirebase-cee89.appspot.com',
    iosBundleId: 'com.example.skillboxfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAczZs5PU0mxcSky5qH4bX56Jw5ZNZSZdg',
    appId: '1:878715841820:ios:6a1385bdd23e7e92dbded9',
    messagingSenderId: '878715841820',
    projectId: 'skillboxfirebase-cee89',
    storageBucket: 'skillboxfirebase-cee89.appspot.com',
    iosBundleId: 'com.example.skillboxfirebaseapp.RunnerTests',
  );
}
